#!/usr/bin/env bash

mkdir -p build
pushd build
cmake -DCMAKE_BUILD_TYPE=Release -DVisuals_DrawType="Textmode" -DVACBypass=1 -DEnableWarnings=1 .
numcpu=$(grep -c ^processor /proc/cpuinfo)
make -j$numcpu
if ! [ -e "bin/libcathook.so" ]; then
    echo "FATAL: Build failed"
    exit
fi
popd
sudo mkdir -p "/opt/cathook/bin/"
sudo cp "build/bin/libcathook.so" "/opt/cathook/bin/libcathook-textmode.so"
